language: node_js
node_js: 
  - "stable"
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=traeghiteslozae
    - DB_USERNAME=codeblock
    - DB_PASSWORD=codekey
    - DBNAME=bankr_testdb
services:
- postgresql
before_script:
- psql -c 'create database bankr_testdb;' -U postgres
- psql -c "CREATE USER codeblock WITH PASSWORD 'codekey';" -U postgres
cache:
  directories:
    - "node_modules"
script: npm test
after_success: 'npm run coverage'
after_failure: 'cat /home/travis/.npm/_logs/2019-04-*-debug.log'
